name: Manual Build and Release Fonts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev pkg-config

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build fonts from .glyphspackage
      run: |
        mkdir -p output
        PKG=$(find sources -name "*.glyphspackage" | head -n 1)
        if [ -z "$PKG" ]; then
          echo "No .glyphspackage found in sources/. Aborting."
          exit 1
        fi
        echo "Using $PKG"

        # Build all instance OTF and TTF fonts, fixing overlaps
        fontmake -g "$PKG" -o otf --output-dir output --fix-overlaps
        fontmake -g "$PKG" -o ttf --output-dir output --fix-overlaps

        # Build variable font (OTF)
        fontmake -g "$PKG" -o variable --output-dir output --fix-overlaps

    - name: Create GitHub release and upload fonts
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        name: Release ${{ inputs.tag }}
        files: |
          output/*.otf
          output/*.ttf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
